<html>
<head>
    <title>COMP 353 Database Project</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>Add Item</h1>

<form class="pure-form" method="post" action="/index.php/inventory/add">
    <label for="units">Units</label>
    <input name="units" id="units" type="text" size="60" /><br />

    <label for="date">Date</label>
    <input name="date" id="date" type="date" size="60" /><br />

    <label for="price">Price</label>
    <input name="price" id="price" type="text" size="60" /><br />

<label for="item">Items</label>
    <select name="item">
        <option value=""></option>
<?php
    foreach($data['items'] as $item): ?>
        <option value=<?=$item->getId()?>><?=$item->getName()?></option>
<?php
    endforeach;
?>
    </select><br />

    <input type="submit" class="pure-button" value="Create" />
</form>

</body>
</html>