<html>
<head>
    <title>COMP 353 Database Project</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>Inventory</h1>

<a href="/index.php/inventory/add">Add Item</a>

<table class="pure-table">
    <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Units</th>
        <th>Date</th>
        <th>Actions</th>
    </tr>

<?php foreach($data['inventoryItems'] as $invItem): ?>

    <tr>
        <td><?=$invItem->getItem()->getName() ?></td>
        <td><?=$invItem->getPrice() ?></td>
        <td><?=$invItem->getUnits() ?></td>
        <td><?=$invItem->getDate() ?></td>
        <td>
            <a href="/index.php/inventory/<?php echo $invItem->getId(); ?>/edit">Edit</a>
            <a href="/index.php/inventory/<?php echo $invItem->getId(); ?>/delete">Delete</a>
        </td>
    </tr>

<?php endforeach; ?>
</table>
</body>
</html>