<html>
<head>
    <title>COMP 353 Database Project</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>New Dependant</h1>

<form class="pure-form" method="post" action="/index.php/dependant/new">
    <label for="name">Name</label>
    <input name="name" id="name" type="text" size="60" /><br />

    <label for="sin">SIN</label>
    <input name="sin" id="sin" type="text" size="60" /><br />
    
    <label for="dob">DOB</label>
    <input name="dob" id="dob" type="text" size="60" /><br />
</form>
</body>
</html>