<html>
<head>
    <title>COMP 353 Database Project</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>Dependants</h1>

<a href="/index.php/dependant/new">Add New Dependant</a>

<table class="pure-table">
    <tr>
        <th>Name</th>
        <th>SIN</th>
        <th>DOB</th>
        <th>Actions</th>
    </tr>

<?php foreach($data['dependants'] as $dependant): ?>

    <tr>
        <td><?=$dependant->getName() ?></td>
        <td><?=$dependant->getSin() ?></td>
        <td><?=$dependant->getDob() ?></td>
        <td>
            <a href="/index.php/dependant/<?php echo $dependant->getId(); ?>/edit">Edit</a>
            <a href="/index.php/dependant/<?php echo $dependant->getId(); ?>/delete">Delete</a>
        </td>
    </tr>

<?php endforeach; ?>
</table>
</body>
</html>