<html>
<head>
    <title>COMP 353 Database Project</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>New Dependant</h1>

<form class="pure-form" method="post" action="/index.php/dependant/new">
    <label for="name">Name</label>
    <input name="name" id="name" type="text" size="60" /><br />

    <label for="sin">SIN</label>
    <input name="sin" id="sin" type="text" size="60" /><br />
    
    <label for="dob">DOB</label>
    <input name="dob" id="dob" type="date" size="60" /><br />

    <label for="employee">Related Employee</label>
    <select name="employee">
        <option value=""></option>
<?php
    foreach($data['employees'] as $employee): ?>
        <option value=<?=$employee->getId()?>>
            ID: <?=$employee->getId()?> Name: <?=$employee->getName()?>
        </option>
<?php
    endforeach;
?>
    </select><br />
    <input type="submit" class="pure-button" value="Create" />
</form>
</body>
</html>