<html>
<head>
    <title>COMP 353 Database Project</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>New Customer</h1>

<form class="pure-form" method="post" action="/index.php/customer/new">
    <label for="name">Name</label>
    <input name="name" id="name" type="text" size="60" /><br />

    <label for="address">Address</label>
    <input name="address" id="address" type="text" size="60" /><br />

    <label for="phone">Phone</label>
    <input name="phone" id="phone" type="text" size="60" /><br />

    <input type="submit" class="pure-button" value="Create" />
</form>

</body>
</html>