<html>
<head>
    <title>COMP 353 Database Project</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>Edit Customer</h1>
<?php $customer = $data['customer'] ?>
<form class="pure-form" method="post" action="/index.php/customer/edit">
    <input type="hidden" name="id" value="<?php echo $customer->getId(); ?>"/>
    <label for="name">Name</label>
    <input name="name" id="name" type="text" size="60" value="<?php echo $customer->getName(); ?>"/><br />

    <label for="address">Address</label>
    <input name="address" id="address" type="text" size="60" value="<?php echo $customer->getAddress(); ?>"/><br />

    <label for="phone">Phone</label>
    <input name="phone" id="phone" type="text" size="60" value="<?php echo $customer->getPhoneNumber(); ?>"/><br />

    <input type="submit" class="pure-button" value="Create" />
</form>

</body>
</html>