<!DOCTYPE HTML>
<html lang ="en">
    <head>

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <link rel="stylesheet" href="/templates/jonStyle.css">
        <script type="text/javascript" src="/templates/bootstrap.js"></script>

        
        <meta charset="utf-8">
        <title>COMP 353 - Main Project</title>
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top text-center">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="true" aria-controls="navbar">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/index.php/">COMP 353 - Main Project</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse in" aria-expanded="true">
                    <ul class="nav navbar-nav">
                        <li><a href="/index.php/department/query">Department</a></li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Top 3<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="/index.php/products/query">Products</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="/index.php/customers/query">Customers</a></li>
                            </ul>
                        </li>
                        <li><a href="/index.php/inventory/query">Inventory</a></li>
                        <li><a href="/index.php/payments/query">Payments</a></li>
                        <li><a href="/index.php/invoices/query">Invoices</a></li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">CRUD<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="/index.php/customers">Customers</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="/index.php/departments">Departments</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="/index.php/dependants">Dependants</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="/index.php/employees">Employees</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="/index.php/inventory">Inventory</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="/index.php/items">Items</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="/index.php/orders">Orders</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="/index.php/payments">Shipments</a></li>
                            </ul>
                        </li>
                  </ul>
                </div>
            </div>
        </nav>
    <div class="container">
      <div class="jumbotron">     
        <h1>Department</h1>
        <p>Given the code or name of a department, print out details about each employee or employees of a department. Such details include ID, name, status (full-time, parttime), earnings per month, number of dependents.</p>
      </div>    
    </div>
    <div class="container">
      <div class="col-md-12 col-sm-8">
        <div class="panel panel-default">
          <div class="panel-heading text-center"><h4><strong>Department Query</strong></h4></div>
          <div class="panel-body">
            <div class="form-group text-center">
            <!--innerpanels-->
              <div class="col-md-1"></div>
              <div class="col-md-10">
                <form class="form-horizontal" method="post" action="/index.php/department/query">
                  <div class="panel panel-default">
                    <div class="panel-body">
                      <div class="form-group text-center">
                        <label class="col-sm-4 control-label" id="deptLbl">Department: </label>
                        <div class="col-sm-4">
                          <label for="department">Departments</label>
                            <select name="department">
                              <option value=""></option>
                                <?php foreach($data['departments'] as $department): ?>
                              <option value=<?=$department->getid()?>><?=$department->getName()?></option>
                                <?php endforeach;?>
                            </select><br />
                        </div>
                        <div class="col-sm-2">
                          <button type="submit" class="btn btn-default" >Find</button>
                        </div>
                      </div>
                    </div>
                  </div>
                </form>
              </div>
              <div class="col-md-1"></div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <table class="pure-table">
    <tr>
        <th>Name</th>
        <th>Room</th>
        <th>Fax</th>
        <th>Phone One</th>
        <th>Phone Two</th>
    </tr>

<?php foreach($data['departments'] as $department): ?>

    <tr>
        <td><?=$department->getName() ?></td>
        <td><?=$department->getRoom() ?></td>
        <td><?=$department->getFax() ?></td>
        <td><?=$department->getPhoneOne() ?></td>
        <td><?=$department->getPhoneTwo() ?></td>
    </tr>

<?php endforeach; ?>
</table>
  </body>
</html>