<html>
<head>
    <title>COMP 353 Database Project</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>Edit Dependant</h1>
<?php $dependant = $data['dependant'] ?>
<form class="pure-form" method="post" action="/index.php/dependant/edit">
    <input type="hidden" name="id" value="<?php echo $dependant->getId(); ?>"/>
    <label for="name">Name</label>
    <input name="name" id="name" type="text" size="60" value="<?php echo $dependant->getName(); ?>"/><br />

    <label for="sin">SIN</label>
    <input name="sin" id="sin" type="text" size="60" value="<?php echo $dependant->getSin(); ?>"/><br />
    
    <label for="dob">DOB</label>
    <input name="dob" id="dob" type="text" size="60" value="<?php echo $dependant->getDob(); ?>"/><br />
    <input type="submit" class="pure-button" value="Create" />
</form>
</body>
</html>