<html>
<head>
    <title>COMP 353 Database Project</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>Departments</h1>

<p><a href="<?=$router->pathFor('customer-new')?>">Add New Department</a></p>

<table class="pure-table">
    <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Phone Number</th>
        <th>Actions</th>
    </tr>

<?php foreach($data['customers'] as $customer): ?>

    <tr>
        <td><?=$customer->getName() ?></td>
        <td><?=$customer->getAddress() ?></td>
        <td><?=$customer->getPhoneNumber() ?> ...</td>
        <td>
            <a href="<?=$router->pathFor('department-edit', ['id' => $customer->getId()])?>">Edit</a>
            <a href="<?=$router->pathFor('department-delete', ['id' => $customer->getId()])?>">Delete</a>
        </td>
    </tr>

<?php endforeach; ?>
</table>
</body>
</html>