<html>
<head>
    <title>COMP 353 Database Project</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>Departments</h1>

<a href="/index.php/department/new">Add New Department</a>

<table class="pure-table">
    <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Phone Number</th>
        <th>Actions</th>
    </tr>

<?php foreach($data['departments'] as $department): ?>

    <tr>
        <td><?=$department->getName() ?></td>
        <td><?=$department->getRoom() ?></td>
        <td><?=$department->getFax() ?></td>
        <td><?=$department->getPhoneOne() ?></td>
        <td><?=$department->getPhoneTwo() ?></td>
        <td>
            <a href="/index.php/department/<?php echo $department->getId(); ?>/edit">Edit</a>
            <a href="/index.php/department/<?php echo $department->getId(); ?>/delete">Delete</a>
        </td>
    </tr>

<?php endforeach; ?>
</table>
</body>
</html>