<html>
<head>
    <title>COMP 353 Database Project</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>New department</h1>

<form class="pure-form" method="post" action="/index.php/department/new">
    <label for="name">Name</label>
    <input name="name" id="name" type="text" size="60" /><br />

    <label for="room">Room Number</label>
    <input name="room" id="room" type="text" size="60" /><br />
    
    <label for="fax">Fax</label>
    <input name="fax" id="fax" type="text" size="60" /><br />

    <label for="phoneOne">Phone 1</label>
    <input name="phoneOne" id="phoneOne" type="text" size="60" v/><br />

    <label for="phoneTwo">Phone 2</label>
    <input name="phoneTwo" id="phoneTwo" type="text" size="60" /><br />
</form>

</body>
</html>