<html>
<head>
    <title>COMP 353 Database Project</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>Edit Employee</h1>
<?php $employee = $data['employee'] ?>
<form class="pure-form" method="post" action="/index.php/employee/edit">
    <input type="hidden" name="id" value="<?php echo $employee->getId(); ?>"/>
    <label for="name">Name</label>
    <input name="name" id="name" type="text" size="60" value="<?php echo $employee->getName(); ?>"/><br />

    <label for="sin">SIN</label>
    <input name="sin" id="sin" type="text" size="60" value="<?php echo $employee->getSin(); ?>"/><br />
    
    <label for="dob">Date of Birth</label>
    <input name="dob" id="dob" type="text" size="60" value="<?php echo $employee->getDob(); ?>"/><br />

    <label for="phone">Phone</label>
    <input name="phone" id="phone" type="text" size="60" value="<?php echo $employee->getPhone(); ?>"/><br />

    <label for="address">Address</label>
    <input name="address" id="address" type="text" size="60" value="<?php echo $employee->getAddress(); ?>"/><br />

    <label for="position">Position</label>
    <input name="position" id="position" type="text" size="60" value="<?php echo $employee->getPosition(); ?>"/><br />
    <input type="submit" class="pure-button" value="Create" />
</form>
</body>
</html>