<html>
<head>
    <title>COMP 353 Database Project</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>Employees</h1>

<a href="/index.php/employee/new">Add New Employee</a>

<table class="pure-table">
    <tr>
        <th>Name</th>
        <th>SIN</th>
        <th>Date of Birth</th>
        <th>Address</th>
        <th>Phone</th>
        <th>Position</th>
        <th>Actions</th>
    </tr>

<?php foreach($data['employees'] as $employee): ?>

    <tr>
        <td><?=$employee->getName() ?></td>
        <td><?=$employee->getSin() ?></td>
        <td><?=$employee->getDob() ?></td>
        <td><?=$employee->getAddress() ?></td>
        <td><?=$employee->getPhone() ?></td>
        <td><?=$employee->getPosition() ?></td>
        <td>
            <a href="/index.php/employee/<?php echo $employee->getId(); ?>/edit">Edit</a>
            <a href="/index.php/employee/<?php echo $employee->getId(); ?>/delete">Delete</a>
        </td>
    </tr>

<?php endforeach; ?>
</table>
</body>
</html>