<html>
<head>
    <title>COMP 353 Database Project</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>New Employee</h1>

<form class="pure-form" method="post" action="/index.php/employee/new">
    <label for="name">Name</label>
    <input name="name" id="name" type="text" size="60" /><br />

    <label for="sin">SIN</label>
    <input name="sin" id="sin" type="text" size="60" /><br />
    
    <label for="dob">Date of Birth</label>
    <input name="dob" id="dob" type="text" size="60" /><br />

    <label for="phone">Phone</label>
    <input name="phone" id="phone" type="text" size="60" /><br />

    <label for="address">Address</label>
    <input name="address" id="address" type="text" size="60" /><br />

    <label for="position">Position</label>
    <input name="position" id="position" type="text" size="60" /><br />

    <label for="email">Email</label>
    <input name="email" id="email" type="text" size="60" /><br />
    <input type="submit" class="pure-button" value="Create" />
</form>

</body>
</html>