<html>
<head>
    <title>COMP 353 Database Project</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>New Employee</h1>

<form class="pure-form" method="post" action="/index.php/employee/new">
    <label for="name">Name</label>
    <input name="name" id="name" type="text" size="60" /><br />

    <label for="sin">SIN</label>
    <input name="sin" id="sin" type="text" size="60" /><br />
    
    <label for="dob">Date of Birth</label>
    <input name="dob" id="dob" type="date" size="60" /><br />

    <label for="phone">Phone</label>
    <input name="phone" id="phone" type="text" size="60" /><br />

    <label for="address">Address</label>
    <input name="address" id="address" type="text" size="60" /><br />

    <label for="position">Position</label>
    <input name="position" id="position" type="text" size="60" /><br />

    <label for="email">Email</label>
    <input name="email" id="email" type="text" size="60" /><br />

    <label for="department">Departments</label>
    <select name="department">
        <option value=""></option>
        <?php foreach($data['departments'] as $department): ?>
            <option value=<?=$department->getId()?>><?=$department->getName()?></option>
        <?php endforeach;?>
    </select><br />

    <label for="manager">Is Manager</label>
    <input type="hidden" name="manager" value="0" />
    <input type="checkbox" name="manager" value="1" />

    <label for="start">Start Date</label>
    <input name="start" id="start" type="date" size="60" /><br />

    <label for="end">End Date</label>
    <input name="end" id="end" type="date" size="60" /><br />

    <input type="submit" class="pure-button" value="Create" />
</form>

</body>
</html>