DROP TABLE IF EXISTS PartTimeEmployee;
DROP TABLE IF EXISTS FullTimeEmployee;
DROP TABLE IF EXISTS IsCareGiver;
DROP TABLE IF EXISTS Inventory;
DROP TABLE IF EXISTS Payment;
DROP TABLE IF EXISTS HasOrdered;
DROP TABLE IF EXISTS HasColor;
DROP TABLE IF EXISTS ItemsOrdered;
DROP TABLE IF EXISTS HasEmployees;
DROP TABLE IF EXISTS Employee;
DROP TABLE IF EXISTS EmployeeDependant;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Item;
DROP TABLE IF EXISTS Colors;
DROP TABLE IF EXISTS Department;

CREATE TABLE Employee (
Id INT(6) PRIMARY KEY,
SSN INT(9) NOT NULL,
Name VARCHAR(30) NOT NULL,
Telephone VARCHAR(12) NOT NULL,
email VARCHAR(50) NOT NULL,
DateOfBirth DATE NOT NULL,
Address VARCHAR(30) NOT NULL,
Position VARCHAR(30) NOT NULL
);

CREATE TABLE EmployeeDependant(
SSN INT(9) PRIMARY KEY,
Name VARCHAR(30) NOT NULL,
DateOfBirth DATE NOT NULL
);

CREATE TABLE Customer(
CustomerNumber INT(10) PRIMARY KEY,
Name VARCHAR(30) NOT NULL,
Telephone VARCHAR(12) NOT NULL,
Address VARCHAR(30) NOT NULL
);

CREATE TABLE Orders(
Id INT(10) PRIMARY KEY,
PaymentMethod ENUM('FULL','INSTALLMENT') NOT NULL,
DateOfPurchase DATE NOT NULL,
Balance FLOAT(10,2) NOT NULL
);

CREATE TABLE Item(
Id INT(10) PRIMARY KEY,
Name VARCHAR(30) NOT NULL
);


CREATE TABLE Colors(
Color VARCHAR(30) PRIMARY KEY
);


CREATE TABLE Department(
Id INT(4) PRIMARY KEY,
Name VARCHAR(30) NOT NULL,
PhoneNumber1 VARCHAR(12) NOT NULL,
PhoneNumber2 VARCHAR(12),
RoomNumber INT(3) NOT NULL,
FaxNumber VARCHAR(12)
);

CREATE TABLE PartTimeEmployee(
Id INT(6) PRIMARY KEY,
HourlyWage FLOAT(4,2) NOT NULL,
Hours INT(2),
FOREIGN KEY(Id) REFERENCES Employee(Id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE FullTimeEmployee(
Id INT(6) PRIMARY KEY,
Wage FLOAT(7,2) NOT NULL,
FOREIGN KEY(Id) REFERENCES Employee(Id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IsCareGiver(
Id INT(6),
SSN INT(9) UNIQUE,
PRIMARY KEY (Id,SSN),
FOREIGN KEY (Id) REFERENCES Employee(Id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (SSN) REFERENCES EmployeeDependant(SSN) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Inventory(
ItemId INT(10) PRIMARY KEY,
Price FLOAT(10,2) NOT NULL,
DateOfManufacture DATE NOT NULL,
Quantity INT(15) NOT NULL,
FOREIGN KEY (ItemId) REFERENCES Item(Id)
);

CREATE TABLE Payment(
OrderId INT(10),
PaymentDate DATE,
Amount FLOAT(10,2) NOT NULL,
PRIMARY KEY (OrderId, PaymentDate),
FOREIGN KEY (OrderID) REFERENCES Orders(Id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE HasOrdered(
CNumber INT(10),
OrderId INT(10),
PRIMARY KEY (CNumber, OrderId),
FOREIGN KEY (CNumber) REFERENCES Customer(CustomerNumber) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (OrderId) REFERENCES Orders(Id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE HasColor(
ItemId INT(10),
Color VARCHAR(30),
PRIMARY KEY (ItemId,Color),
FOREIGN KEY (ItemId) REFERENCES Item(Id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (Color) REFERENCES Colors(Color)
);

CREATE TABLE ItemsOrdered(
OrderId INT(10),
ItemId INT(10),
Quantity INT(4),
PRIMARY KEY (OrderId, ItemId),
FOREIGN KEY (OrderId) REFERENCES Orders(Id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (ItemId) REFERENCES Item(Id)
);

CREATE TABLE HasEmployees(
DeptId INT(4),
EmpId INT(6),
IsManager BOOLEAN NOT NULL,
StartDate DATE NOT NULL,
EndDate DATE,
PRIMARY KEY (DeptId, EmpId),
FOREIGN KEY (DeptId) REFERENCES Department(Id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (EmpId) REFERENCES Employee(Id) ON DELETE CASCADE ON UPDATE CASCADE
);