<html>
<head>
    <title>COMP 353 Database Project</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>Edit Order</h1>
<?php $order = $data['order'] ?>
<form class="pure-form" method="post" action="/index.php/order/edit">
    <input type="hidden" name="id" value="<?php echo $order->getId(); ?>"/>
    <label for="total">Grand Total</label>
    <input name="total" id="total" type="text" size="60" value="<?php echo $order->getTotal(); ?>"/><br />

    <label for="date">Date of Purchase</label>
    <input name="date" id="date" type="text" size="60" value="<?php echo $order->getDate(); ?>"/><br />
    
    <label for="method">Payment Method</label>
    <input name="method" id="method" type="text" size="60" value="<?php echo $order->getMethod(); ?>"/><br />

    <input type="submit" class="pure-button" value="Create" />
</form>
</body>
</html>