<html>
<head>
    <title>COMP 353 Database Project</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>New Order</h1>

<form class="pure-form" method="post" action="/index.php/order/new">
    <label for="total">Grand Total</label>
    <input name="total" id="total" type="text" size="60" /><br />

    <label for="date">Date Purchased</label>
    <input name="date" id="date" type="text" size="60" /><br />
    
    <label for="method">Method of Payment</label>
    <input name="method" id="method" type="text" size="60" /><br />
</form>
</body>
</html>