<html>
<head>
    <title>COMP 353 Database Project</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>Orders</h1>

<a href="/index.php/order/new">Add New Order</a>

<table class="pure-table">
    <tr>
        <th>Grand Total</th>
        <th>Date Purchased</th>
        <th>Method of Payment</th>
        <th>Actions</th>
    </tr>

<?php foreach($data['orders'] as $order): ?>

    <tr>
        <td><?=$order->getTotal() ?></td>
        <td><?=$order->getDate() ?></td>
        <td><?=$order->getMethod() ?></td>
        <td>
            <a href="/index.php/order/<?php echo $order->getId(); ?>/edit">Edit</a>
            <a href="/index.php/order/<?php echo $order->getId(); ?>/delete">Delete</a>
        </td>
    </tr>

<?php endforeach; ?>
</table>
</body>
</html>