<html>
<head>
    <title>COMP 353 Database Project</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>Add Shipment</h1>

<form class="pure-form" method="post" action="/index.php/payment/add">
    <label for="date">Date</label>
    <input name="date" id="date" type="date" size="60" /><br />

    <label for="amount">Amount</label>
    <input name="amount" id="amount" type="text" size="60" /><br />

<label for="item">Orders</label>
    <select name="order">
        <option value=""></option>
<?php
    foreach($data['orders'] as $order): ?>
        <option value=<?=$order->getId()?>>
            ID: <?=$order->getId()?> Total:<?=$order->getTotal()?> Date: <?=$order->getDate()?> Method: <?=$order->getMethod()?>
        </option>
<?php
    endforeach;
?>
    </select><br />

    <input type="submit" class="pure-button" value="Create" />
</form>

</body>
</html>