<html>
<head>
    <title>COMP 353 Database Project</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>Edit Shipment</h1>
<?php $payment = $data['payment'] ?>
<form class="pure-form" method="post" action="/index.php/payment/edit">
    <input type="hidden" name="id" value="<?php echo $payment->getId(); ?>"/>
    <label for="amount">Amount</label>
    <input name="amount" id="amount" type="text" size="60" value="<?php echo $payment->getAmount(); ?>"/><br />

    <label for="date">Date</label>
    <input name="date" id="date" type="date" size="60" value="<?php echo $payment->getDate(); ?>"/><br />
    
    <input type="submit" class="pure-button" value="Create" />
</form>
</body>
</html>