<html>
<head>
    <title>COMP 353 Database Project</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>Shipments</h1>

<a href="/index.php/payment/add">Add Shipment</a>

<table class="pure-table">
    <tr>
        <th>Order Number</th>
        <th>Amount</th>
        <th>Date</th>
        <th>Actions</th>
    </tr>

<?php foreach($data['payments'] as $payment): ?>

    <tr>
        <td><?=$payment->getId() ?></td>
        <td><?=$payment->getAmount() ?></td>
        <td><?=$payment->getDate() ?></td>
        <td>
            <a href="/index.php/payment/<?php echo $payment->getId(); ?>/edit">Edit</a>
            <a href="/index.php/payment/<?php echo $payment->getId(); ?>/delete">Delete</a>
        </td>
    </tr>

<?php endforeach; ?>
</table>
</body>
</html>