<html>
<head>
    <title>COMP 353 Database Project</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>Edit Item</h1>
<?php $item = $data['item'] ?>
<form class="pure-form" method="post" action="/index.php/item/edit">
    <input type="hidden" name="id" value="<?php echo $item->getId(); ?>"/>
    <label for="name">Name</label>
    <input name="name" id="name" type="text" size="60" value="<?php echo $item->getName(); ?>"/><br />

<label for="color">Colors</label>
    <select name="color">
        <option value=""></option>
<?php
    foreach($data['colors'] as $color): ?>
        <option value=<?=$color->getName()?>><?=$color->getName()?></option>
<?php
    endforeach;
?>
    </select><br />
    
    <input type="submit" class="pure-button" value="Create" />
</form>
</body>
</html>