<html>
<head>
    <title>COMP 353 Database Project</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>New Item</h1>

<form class="pure-form" method="post" action="/index.php/item/new">
    <label for="name">Name</label>
    <input name="name" id="name" type="text" size="60" /><br />

<!--     <label for="color">Colors</label>
    <select name="color">
        <option value=""></option>
<?php
    foreach($data['colors'] as $color): ?>
        <option value=<?=$color->getId()?>><?=$color->getName()?></option>
<?php
    endforeach;
?>
    </select><br /> -->

    <input type="submit" class="pure-button" value="Create" />
</form>

</body>
</html>