<html>
<head>
    <title>COMP 353 Database Project</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>Items</h1>

<a href="/index.php/item/new">Add New Item</a>

<table class="pure-table">
    <tr>
        <th>Name</th>
        <th>Actions</th>
    </tr>

<?php foreach($data['items'] as $item): ?>

    <tr>
        <td><?=$item->getName() ?></td>
        <td>
            <a href="/index.php/item/<?php echo $item->getId(); ?>/edit">Edit</a>
            <a href="/index.php/item/<?php echo $item->getId(); ?>/delete">Delete</a>
        </td>
    </tr>

<?php endforeach; ?>
</table>
</body>
</html>